[package]
name = "trees"
version = "0.1.0"
edition = "2021"

[dependencies]
#local
database = { path = "../database" }

#newtypes

#utils
anyhow = { workspace = true }
thiserror = { workspace = true }
sha2 = "0.10.6"
integer-encoding = "3.0.4"

#serialization

#other
caches = "0.2.4"

[dev-dependencies]
hex = "0.4.3"
criterion = "0.5.1"
rand = "0.8.5"
pprof = { version = "0.13.0", features = ["flamegraph", "criterion"] }
handlebars = "5.1.0"
serde = "1.0.176"
serde_json = "1.0.104"

[[bench]]
name = "iavl_benchmark"
harness = false

[[example]]
name = "benchtable"
test = true
