[package]
name = "proto-messages"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.8"
ibc-proto = { workspace = true }
proto-types = { path = "../proto-types" }
cosmwasm-std = "1.1.5"
thiserror = "1.0.13"
sha2 = "0.10.6"
ripemd = "0.1.3"
serde = { version = "1.0", default-features = false }
serde-aux = "4.2.0"
tendermint-informal = { package = "tendermint", git = "https://github.com/joneskm/tendermint-rs" }
base64 = "0.21.0"
base64-serde = "0.7.0"
serde_with = "3.0.0"
secp256k1 = { version = "0.25.0", features = ["bitcoin-hashes"] }
nutype = { version = "0.3.1" , features = [ "serde"]}
byteorder = "1.5.0"
micromarshal = "0.4.1"

[dev-dependencies]
hex = "0.4.3"
serde_json = "1.0.93"
data-encoding = "2.4.0"
